spring:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        limit: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        delete-dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  datasource:
    url: jdbc:postgresql://localhost:5433/search-engine
    username: search-engine
    password: search-engine
    driverClassName: org.postgresql.Driver

indexing-settings:
  sites:
#    - url: https://lenta.ru
#      name: Лента.ру
    - url: https://skillbox.ru
      name: Skillbox
    - url: https://playback.ru
      name: PlayBack.Ru

connection-config:
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
  referer: http://google.ru
