spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5433/search-engine
    username: search-engine
    password: search-engine
    driverClassName: org.postgresql.Driver
indexing-settings:
  sites:
#    - url: http://lenta.ru
#      name: Лента.ру
#    - url: https://skillbox.ru
#      name: Skillbox
    - url: http://музей-ямщика.рф
      name: Музей Ямщика
    - url: https://playback.ru
      name: PlayBack.Ru

connection-config:
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
  referer: https://skillbox.ru