connection-config:
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
  referer: http://google.ru

indexing-settings:
  sites:
     - url: http://музей-ямщика.рф
       name: Музей Ямщика
